### ISSUE TITLE
Update AFNetworking to 1.3

### ISSUE THREAD

**Issue by rispie** [danielebogo/PSUpdateApp#3]
AFNetworking 1.3 was released a couple of days ago.

**Comment by danielebogo** [comment]
Thanks a lot. I'll update it asap.

**Comment by danielebogo** [comment]
Update to 1.0.6 done.
PullRequest to Cocoapods done. I'm waiting their response to merge my request.

**Comment by rispie** [comment]
Thanks a lot!

**Comment by danielebogo** [comment]
This version is available on Cocoapods!
