### ISSUE TITLE
Unable to customize text in UIAlertView

### ISSUE THREAD

**Issue by ryansmith3136** [danielebogo/PSUpdateApp#8]
I am unable to find an API that would allow me to provide my own text for the upgrade message.

**Comment by danielebogo** [comment]
Hi @ryandotsmith , that's true, because you can use your alert in the completion block of detectAppVersion: . But i can add this simple API. Is not a problem.

**Comment by ryansmith3136** [comment]
Awesome! I am looking forward to the new API.

**Comment by danielebogo** [comment]
Ok, i've updated the project. You can find a property to set the title and 3 properties (one for every UpdateStrategies) to set the message.
