### ISSUE TITLE
How to support ios 5?

### ISSUE THREAD

**Issue by xhzengAIB** [danielebogo/PSUpdateApp#9]
Hi! @danielebogo

**Comment by danielebogo** [comment]
You can find the project for the targets < iOS 6 Based on AFNetworking 1.3.3

**Comment by xhzengAIB** [comment]
You're right, abandons the ios 5.

**Comment by danielebogo** [comment]
Yes, i don't want to support iOS 5. But if you want to use this library with iOS 5, this is the right project folder: https://github.com/danielebogo/PSUpdateApp/tree/master/PSUpdateApp (using AFNetworking 1.3.3)

**Comment by xhzengAIB** [comment]
Hi！ @danielebogo  
 thanks you

Jack
